### PR TITLE
Added hook for copying galaxy extra files

### PR DESCRIPTION
**Pull request by nuwang**

### CODE REVIEW

**Comment by afgane** [comment]
Could you also add this to README and into defaults?

**Comment by nuwang** [comment]
Are you suggesting that we should remove: "when: cmg_extra_files is defined" and just define an empty variable in defaults? Will add it to readme.

**Comment by afgane** [comment]
I'd say that having an empty list in defaults without the `when` clause is preferable so it's more clear to anyone looking at it?

**Comment by nuwang** [comment]
Sounds good. Done.

**Comment by afgane** [comment]
Also updated in Galaxy Ansible: https://galaxy.ansible.com/list#/roles/2916

**Pull request merged**
